accounts/urls.py
from django.urls import path
from .views import LoginView, LogoutView

app_name = 'accounts'
urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('polls.urls')),
    path('user/', include('accounts.urls')),
    path('admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

polls/urls.py
from django.urls import path
from .views import HomeView, VoteView, ResultView, CategoryView, ModalView

app_name = 'polls'
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('vote/<int:pk>/', VoteView.as_view(), name='vote'),
    path('result/<str:category>/', ResultView.as_view(), name='result'),
    path('category/<str:category>/', CategoryView.as_view(), name='category'),
    path('modal_content/<int:pk>/', ModalView.as_view(), name='modal_view'),
]

accounts/models.py
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    pass

polls/models.py
from django.db import models
from django.contrib.auth import get_user_model


class Category(models.Model):
    category_name = models.CharField(max_length=120)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.category_name


class Candidate(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField(max_length=120)
    image = models.ImageField(upload_to='static/images')
    num_of_votes = models.IntegerField(default=0)

    def __str__(self):
        return self.name


class Vote(models.Model):
    voter = models.ForeignKey(get_user_model(), on_delete=models.CASCADE,
                              related_name="votes")
    category = models.ForeignKey(Category, on_delete=models.CASCADE,
                                 related_name="votes")

    def __str__(self):
        return f"{self.voter} - {self.category}"

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, logout, login
from django.views import View


class LoginView(View):
    def get(self, request):
        if request.user.is_authenticated:
            return redirect('polls:home')
        return render(request, 'login.html')

    def post(self, request):
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('polls:home')
        else:
            return redirect('accounts:login')


class LogoutView(View):
    def get(self, request):
        logout(request)
        return redirect('accounts:login')

polls/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import get_user_model
from django.contrib import messages
from django.http import JsonResponse
from django.db.models import F
from django.views import View
from .models import Category, Candidate, Vote


class HomeView(LoginRequiredMixin, View):
    def get(self, request):
        return render(request, "index.html")


class CategoryView(LoginRequiredMixin, View):

    def get(self, request, category):
        if category == "Vice":
            category = "Vice President"

        user = get_user_model().objects.get(username=request.user.username)
        category = Category.objects.get(category_name=category)

        if Vote.objects.filter(voter=user, category=category).first():
            return redirect("polls:result", category=category)

        candidates = category.candidate_set.all()
        context = {
            "candidates": candidates,
            "category": category,
        }
        return render(request, "vote.html", context)


class VoteView(LoginRequiredMixin, View):
    def get(self, request, pk):

        user = get_user_model().objects.get(username=request.user.username)
        candidate = get_object_or_404(Candidate, pk=pk)

        if Vote.objects.filter(voter=user, category=candidate.category).first():
            messages.error(request, "You have already voted for this category! You can't vote twice")
            return redirect("polls:result", category=candidate.category)

        candidate.num_of_votes = F("num_of_votes") + 1
        candidate.save()
        candidate.refresh_from_db()
        Vote.objects.create(voter=user, category=candidate.category)
        messages.success(request, "You have successfuly voted for this category!")
        return redirect("polls:result", category=candidate.category)


class ResultView(LoginRequiredMixin, View):
    def get(self, request, category):

        if category == "Vice":
            category = "Vice President"

        category = Category.objects.get(category_name=category)
        candidates = category.candidate_set.all()
        context = {
            "candidates": candidates,
            "category": category,
        }
        return render(request, "results.html", context)


class ModalView(LoginRequiredMixin, View):
    def get(self, request, pk):
        candidate = get_object_or_404(Candidate, pk=pk)

        link = f"/vote/{candidate.pk}"
        data = {
            "name": candidate.name,
            "image": candidate.image.url,
            "link": link,
        }
        return JsonResponse(data)

templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Voting app</title>
    <meta name="twitter:description" content="Online voting system created with Django and Bootstrap">
    <meta name="twitter:image" content="{% static 'images/220113-G-WC787-004.webp' %}">
    <meta property="og:type" content="website">
    <meta name="description" content="Online votin Application">
    <meta property="og:image" content="{% static 'images/220113-G-WC787-004.webp' %}">
    <meta name="twitter:card" content="summary">
    <meta name="twitter:title" content="Voting app">
    <link rel="stylesheet" href="{% static 'bootstrap/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,400;0,700;1,400&amp;display=swap">
    <link rel="stylesheet" href="{% static 'animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/Login-Form-Basic-icons.css' %}">
    <link rel="stylesheet" href="{% static 'css/untitled.css' %}">
</head>

<body style="font-family: Lato, sans-serif;">
    <div class="container pt-2 pt-md-4">
       
       {% block sidebar %}
         <!-- SIDEBAR -->
        <aside><a class="btn btn-primary fw-bolder text-center bounce animated mybutton" role="button" data-bs-toggle="offcanvas" href="#offcanvasExample" aria-controls="offcanvasExample"><svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" viewBox="0 0 16 16" class="bi bi-arrow-bar-right fs-5 text-center" style="--bs-warning: #f39c12;--bs-warning-rgb: 243,156,18;">
                    <path fill-rule="evenodd" d="M6 8a.5.5 0 0 0 .5.5h5.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3a.5.5 0 0 0 0-.708l-3-3a.5.5 0 0 0-.708.708L12.293 7.5H6.5A.5.5 0 0 0 6 8zm-2.5 7a.5.5 0 0 1-.5-.5v-13a.5.5 0 0 1 1 0v13a.5.5 0 0 1-.5.5z"></path>
                </svg></a>
            <div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasExample" aria-labelledby="offcanvasExampleLabel"><a class="btn btn-primary fw-bolder text-center mybutton" role="button" data-bs-toggle="offcanvas" href="#offcanvasExample" aria-controls="offcanvasExample"><svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" viewBox="0 0 16 16" class="bi bi-arrow-bar-left fs-5 text-center" style="font-size: 11px;">
                        <path fill-rule="evenodd" d="M12.5 15a.5.5 0 0 1-.5-.5v-13a.5.5 0 0 1 1 0v13a.5.5 0 0 1-.5.5zM10 8a.5.5 0 0 1-.5.5H3.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L3.707 7.5H9.5a.5.5 0 0 1 .5.5z"></path>
                    </svg></a>
                <div class="offcanvas-header d-flex d-lg-flex justify-content-center align-items-center mb-0">
                    <h5 id="offcanvasExampleLabel" class="offcanvas-title mt-2"><img class="img-fluid" src="{% static 'images/220113-G-WC787-004.webp' %}" width="100" height="100"></h5>
                </div>
                <h5 class="fw-normal text-center mb-3 mb-md-5">Online Voting App</h5>
                <hr class="mb-0">
                <div class="offcanvas-body p-0">
                    <a href="{% url 'polls:category' 'President' %}">
                        <p class="lead text-start text-light text-bg-primary border rounded-0 border-secondary p-3 mb-0 border-start-0 border-end-0 category_link "><svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" viewBox="0 0 16 16" class="bi bi-people">
                                <path d="M15 14s1 0 1-1-1-4-5-4-5 3-5 4 1 1 1 1h8zm-7.978-1A.261.261 0 0 1 7 12.996c.001-.264.167-1.03.76-1.72C8.312 10.629 9.282 10 11 10c1.717 0 2.687.63 3.24 1.276.593.69.758 1.457.76 1.72l-.008.002a.274.274 0 0 1-.014.002H7.022zM11 7a2 2 0 1 0 0-4 2 2 0 0 0 0 4zm3-2a3 3 0 1 1-6 0 3 3 0 0 1 6 0zM6.936 9.28a5.88 5.88 0 0 0-1.23-.247A7.35 7.35 0 0 0 5 9c-4 0-5 3-5 4 0 .667.333 1 1 1h4.216A2.238 2.238 0 0 1 5 13c0-1.01.377-2.042 1.09-2.904.243-.294.526-.569.846-.816zM4.92 10A5.493 5.493 0 0 0 4 13H1c0-.26.164-1.03.76-1.724.545-.636 1.492-1.256 3.16-1.275zM1.5 5.5a3 3 0 1 1 6 0 3 3 0 0 1-6 0zm3-2a2 2 0 1 0 0 4 2 2 0 0 0 0-4z"></path>
                            </svg>&nbsp;President&nbsp;
                            <span class="badge bg-success fw-light {% if not 'President' in user.voted.split %}invisible{% endif %}">Voted</span></p>   
                    </a>
                    <a href="{% url 'polls:category' 'Vice' %}">
                        <p class="lead text-start text-light text-bg-primary border rounded-0 border-secondary p-3 mb-0 border-start-0 border-end-0 category_link "><svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" viewBox="0 0 16 16" class="bi bi-people">
                                <path d="M15 14s1 0 1-1-1-4-5-4-5 3-5 4 1 1 1 1h8zm-7.978-1A.261.261 0 0 1 7 12.996c.001-.264.167-1.03.76-1.72C8.312 10.629 9.282 10 11 10c1.717 0 2.687.63 3.24 1.276.593.69.758 1.457.76 1.72l-.008.002a.274.274 0 0 1-.014.002H7.022zM11 7a2 2 0 1 0 0-4 2 2 0 0 0 0 4zm3-2a3 3 0 1 1-6 0 3 3 0 0 1 6 0zM6.936 9.28a5.88 5.88 0 0 0-1.23-.247A7.35 7.35 0 0 0 5 9c-4 0-5 3-5 4 0 .667.333 1 1 1h4.216A2.238 2.238 0 0 1 5 13c0-1.01.377-2.042 1.09-2.904.243-.294.526-.569.846-.816zM4.92 10A5.493 5.493 0 0 0 4 13H1c0-.26.164-1.03.76-1.724.545-.636 1.492-1.256 3.16-1.275zM1.5 5.5a3 3 0 1 1 6 0 3 3 0 0 1-6 0zm3-2a2 2 0 1 0 0 4 2 2 0 0 0 0-4z"></path>
                            </svg>&nbsp;Vice President&nbsp;
                            <span class="badge bg-success fw-light {% if not 'Vice' in user.voted.split %}invisible{% endif %}">Voted</span></p>   
                    </a>
                    <a href="{% url 'polls:category' 'Secretary' %}">
                        <p class="lead text-start text-light text-bg-primary border rounded-0 border-secondary p-3 mb-0 border-start-0 border-end-0 category_link "><svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" viewBox="0 0 16 16" class="bi bi-people">
                                <path d="M15 14s1 0 1-1-1-4-5-4-5 3-5 4 1 1 1 1h8zm-7.978-1A.261.261 0 0 1 7 12.996c.001-.264.167-1.03.76-1.72C8.312 10.629 9.282 10 11 10c1.717 0 2.687.63 3.24 1.276.593.69.758 1.457.76 1.72l-.008.002a.274.274 0 0 1-.014.002H7.022zM11 7a2 2 0 1 0 0-4 2 2 0 0 0 0 4zm3-2a3 3 0 1 1-6 0 3 3 0 0 1 6 0zM6.936 9.28a5.88 5.88 0 0 0-1.23-.247A7.35 7.35 0 0 0 5 9c-4 0-5 3-5 4 0 .667.333 1 1 1h4.216A2.238 2.238 0 0 1 5 13c0-1.01.377-2.042 1.09-2.904.243-.294.526-.569.846-.816zM4.92 10A5.493 5.493 0 0 0 4 13H1c0-.26.164-1.03.76-1.724.545-.636 1.492-1.256 3.16-1.275zM1.5 5.5a3 3 0 1 1 6 0 3 3 0 0 1-6 0zm3-2a2 2 0 1 0 0 4 2 2 0 0 0 0-4z"></path>
                            </svg>&nbsp;Secretary&nbsp;
                            <span class="badge bg-success fw-light {% if not 'Secretary' in user.voted.split %}invisible{% endif %}">Voted</span></p>   
                    </a>
                    <a href="{% url 'polls:category' 'Treasurer' %}">
                        <p class="lead text-start text-light text-bg-primary border rounded-0 border-secondary p-3 mb-0 border-start-0 border-end-0 category_link "><svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" viewBox="0 0 16 16" class="bi bi-people">
                                <path d="M15 14s1 0 1-1-1-4-5-4-5 3-5 4 1 1 1 1h8zm-7.978-1A.261.261 0 0 1 7 12.996c.001-.264.167-1.03.76-1.72C8.312 10.629 9.282 10 11 10c1.717 0 2.687.63 3.24 1.276.593.69.758 1.457.76 1.72l-.008.002a.274.274 0 0 1-.014.002H7.022zM11 7a2 2 0 1 0 0-4 2 2 0 0 0 0 4zm3-2a3 3 0 1 1-6 0 3 3 0 0 1 6 0zM6.936 9.28a5.88 5.88 0 0 0-1.23-.247A7.35 7.35 0 0 0 5 9c-4 0-5 3-5 4 0 .667.333 1 1 1h4.216A2.238 2.238 0 0 1 5 13c0-1.01.377-2.042 1.09-2.904.243-.294.526-.569.846-.816zM4.92 10A5.493 5.493 0 0 0 4 13H1c0-.26.164-1.03.76-1.724.545-.636 1.492-1.256 3.16-1.275zM1.5 5.5a3 3 0 1 1 6 0 3 3 0 0 1-6 0zm3-2a2 2 0 1 0 0 4 2 2 0 0 0 0-4z"></path>
                            </svg>&nbsp;Treasurer&nbsp;
                            <span class="badge bg-success fw-light {% if not 'Treasurer' in user.voted.split %}invisible{% endif %}">Voted</span></p>   
                    </a>
                    <a href="{% url 'polls:category' 'WOCOM' %}">
                        <p class="lead text-start text-light text-bg-primary border rounded-0 border-secondary p-3 mb-0 border-start-0 border-end-0 category_link "><svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" viewBox="0 0 16 16" class="bi bi-people">
                                <path d="M15 14s1 0 1-1-1-4-5-4-5 3-5 4 1 1 1 1h8zm-7.978-1A.261.261 0 0 1 7 12.996c.001-.264.167-1.03.76-1.72C8.312 10.629 9.282 10 11 10c1.717 0 2.687.63 3.24 1.276.593.69.758 1.457.76 1.72l-.008.002a.274.274 0 0 1-.014.002H7.022zM11 7a2 2 0 1 0 0-4 2 2 0 0 0 0 4zm3-2a3 3 0 1 1-6 0 3 3 0 0 1 6 0zM6.936 9.28a5.88 5.88 0 0 0-1.23-.247A7.35 7.35 0 0 0 5 9c-4 0-5 3-5 4 0 .667.333 1 1 1h4.216A2.238 2.238 0 0 1 5 13c0-1.01.377-2.042 1.09-2.904.243-.294.526-.569.846-.816zM4.92 10A5.493 5.493 0 0 0 4 13H1c0-.26.164-1.03.76-1.724.545-.636 1.492-1.256 3.16-1.275zM1.5 5.5a3 3 0 1 1 6 0 3 3 0 0 1-6 0zm3-2a2 2 0 1 0 0 4 2 2 0 0 0 0-4z"></path>
                            </svg>&nbsp;WOCOM&nbsp;
                            <span class="badge bg-success fw-light {% if not 'WOCOM' in user.voted.split %}invisible{% endif %}">Voted</span></p>   
                    </a>

                    

                    
                    {% if user.is_authenticated %}
                    <a class="btn btn-danger fs-5 fw-semibold text-center border rounded-0 d-block mt-4 py-3" role="button" href="{% url 'accounts:logout' %}"><svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" viewBox="0 0 16 16" class="bi bi-lock-fill">
                            <path d="M8 1a2 2 0 0 1 2 2v4H6V3a2 2 0 0 1 2-2zm3 6V3a3 3 0 0 0-6 0v4a2 2 0 0 0-2 2v5a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V9a2 2 0 0 0-2-2z"></path>
                        </svg>&nbsp;Logout
                    </a>
                    {% else %}
                    <a class="btn btn-success fs-5 fw-semibold text-center border rounded-0 d-block mt-4 py-3" role="button" href="#"><svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" viewBox="0 0 16 16" class="bi bi-unlock-fill">
                            <path d="M11 1a2 2 0 0 0-2 2v4a2 2 0 0 1 2 2v5a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V9a2 2 0 0 1 2-2h5V3a3 3 0 0 1 6 0v4a.5.5 0 0 1-1 0V3a2 2 0 0 0-2-2z"></path>
                        </svg>&nbsp;Login
                    </a>
                    {% endif %}
                </div>
            </div>
        </aside>
        {% endblock sidebar %}

        {% block header %}
        <header class="text-center text-primary bg-light p-5"><img class="rounded img-fluid mb-4" src="{% static 'images/220113-G-WC787-004.webp' %}" width="200" height="200">
            <h1 class="fw-semibold text-primary bg-light mb-3">Voting Portal</h1>
            <div><span class="badge bg-success fs-6 text-center mb-1">Voting Underway</span></div>
            <p class="text-danger">00 hrs : 00 mins left.</p>
        </header><!-- Start: main-body -->
        {% endblock header %}

        
        {% block main-body %}
            
        <section class="pt-3">
            <div class="text-center d-md-flex flex-column justify-content-md-center align-items-md-center">
                <div class="alert alert-light fs-5 fw-normal text-start text-primary border rounded-0 border-4 border-primary border-end-0 border-top-0 border-bottom-0" role="alert"><span class="fw-normal"><strong>Click on the button at the top left corner to select category and vote!</strong>&nbsp;</span></div>
            </div>
        </section><!-- End: main-body -->
        {% endblock main-body %}
    </div>
    <script src="{% static 'bootstrap/bootstrap.min.js' %}"></script>
    <script src="{% static '/js/bs-init.js' %}"></script>
</body>

</html>

templates/login.html
{% extends 'index.html' %}


{% block sidebar %}  
{% endblock sidebar %}
{% block main-body %}
{% endblock main-body %}
    

    
    {% block header %}
        
    <!-- Start: Login Form Basic -->
    <section class="py-4 py-xl-5">
        <div class="container bg-light">
            <div class="row mb-3">
                <div class="col-md-8 col-xl-6 text-center mx-auto">
                    <h2 class="fw-semibold text-primary">Voting Portal</h2>
                    <p class="fs-5 fw-semibold text-primary">Please Login to vote!</p>
                </div>
            </div>
            <div class="row d-flex justify-content-center">
                <div class="col-md-6">
                    <div class="card mb-5">
                        <div class="card-body d-flex flex-column align-items-center">
                            <div class="bs-icon-xl bs-icon-circle bs-icon-primary bs-icon my-4"><svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" viewBox="0 0 16 16" class="bi bi-person">
                                    <path d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z"></path>
                                </svg></div>
                            <form class="text-center" method="post" action="{% url 'accounts:login' %}">
                                {% csrf_token %}
                                <div class="mb-3"><input class="form-control" type="text" name="username" placeholder="Username"></div>
                                <div class="mb-3"><input class="form-control" type="password" name="password" placeholder="Password"></div>
                                <div class="mb-3"><button class="btn btn-primary d-block w-100" type="submit"><svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" viewBox="0 0 16 16" class="bi bi-unlock-fill">
                                            <path d="M11 1a2 2 0 0 0-2 2v4a2 2 0 0 1 2 2v5a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V9a2 2 0 0 1 2-2h5V3a3 3 0 0 1 6 0v4a.5.5 0 0 1-1 0V3a2 2 0 0 0-2-2z"></path>
                                        </svg>&nbsp;Login</button></div>
                                <p class="text-muted">Forgot your password?</p>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <div class="text-center"><span class="badge bg-success fs-6 text-center mb-1">Voting Underway</span></div>
            <p class="text-center text-danger">00 hrs : 00 mins left.</p>
        </div>
    </section><!-- End: Login Form Basic -->
    {% endblock header %}
    
    
 
        

templates/results.html
{% extends 'vote.html' %}

{% block modal %}
{% endblock modal %}
    


 
    <!-- <button class="btn btn-lg disabled" type="button" data-bs-toggle="modal" data-bs-target="#staticBackdrop" disabled="">{{ candidate.num_of_votes }}</button> -->
           
    {% block result %}
    
    {% if messages %}
    {% for message in messages %}
        <section class="pt-3 mb-1">
            <div class="text-center d-md-flex flex-column justify-content-md-center align-items-md-center">
                <div class="alert alert-light fs-5 fw-normal text-start text-{{message.tags}} border rounded-0 border-4 border-{{message.tags}} border-end-0 border-top-0 border-bottom-0" role="alert"><span class="fw-normal"><strong>{{ message }}</strong>&nbsp;</span></div>
            </div>
        </section><!-- End: main-body -->
    {% endfor %}
    {% endif %}
    
        <div class="row gx-0 gy-5 row-cols-md-2 mt-2">
            {% for candidate in candidates %}   
            <div class="col">
                <div class="text-center"><img class="mb-1" src="{{ candidate.image.url }}" width="250" height="250">
                    <p class="fs-5 fw-semibold text-primary mb-2">{{ candidate.name }}</p>
                    <button class="btn btn-lg disabled" type="button" data-bs-toggle="modal" data-bs-target="#staticBackdrop" disabled="">{{ candidate.num_of_votes }}</button>
                </div>
            </div>
            {% endfor %}
        </div><!-- End: Candidates -->
        {% endblock result %}

templates/vote.html
{% extends 'index.html' %}

        
        {% block header %}  
        <header class="text-center text-primary bg-light p-4">
            <h1 class="fw-semibold text-primary bg-light mb-3">{{ category }}</h1>
            <div><span class="badge bg-success fs-6 text-center mb-1">Voting Underway</span></div>
            <p class="text-danger">00 hrs : 00 mins left.</p>
        </header><!-- End: Header -->
        {% endblock header %}
        
        
           
        {% block main-body %}
        <!-- Start: Candidates -->
        {% block result %}
        <div class="row gx-0 gy-5 row-cols-md-2 mt-2">
            {% for candidate in candidates %}   
            <div class="col">
                <div class="text-center"><img class="mb-1" src="{{ candidate.image.url }}" width="250" height="250">
                    <p class="fs-5 fw-semibold text-primary mb-2">{{ candidate.name }}</p>
                    
                      
                    <button class="btn btn-success" type="button" data-bs-toggle="modal" data-bs-target="#staticBackdrop" data-bs-id="{{ candidate.pk }}"><svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" viewBox="0 0 16 16" class="bi bi-check2-square">
                            <path d="M3 14.5A1.5 1.5 0 0 1 1.5 13V3A1.5 1.5 0 0 1 3 1.5h8a.5.5 0 0 1 0 1H3a.5.5 0 0 0-.5.5v10a.5.5 0 0 0 .5.5h10a.5.5 0 0 0 .5-.5V8a.5.5 0 0 1 1 0v5a1.5 1.5 0 0 1-1.5 1.5H3z"></path>
                            <path d="m8.354 10.354 7-7a.5.5 0 0 0-.708-.708L8 9.293 5.354 6.646a.5.5 0 1 0-.708.708l3 3a.5.5 0 0 0 .708 0z"></path>
                        </svg>&nbsp;Vote
                    </button>
                </div>
            </div>
            {% endfor %}
        </div><!-- End: Candidates -->
        {% endblock result %}

        
        {% block modal %} 
        {% for candidate in candidates %}
         <!-- Start: modal -->
         <section>
            <div class="modal fade" role="dialog" tabindex="-1" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" aria-labelledby="staticBackdropLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="fw-semibold text-primary modal-title" id="staticBackdropLabel">Confirm vote for</h5>
                        </div>
                        <div class="modal-body">  
                        </div>
                        <div class="modal-footer">
                        </div>
                    </div>
                </div>
            </div>
        </section><!-- End: modal -->
        {% endfor %}
        {% endblock modal %}
        {% endblock main-body %}